### ISSUE TITLE
npm部署過程中報錯

### ISSUE THREAD

**Issue by BH6AOV** [ayamomiji/kyaru-concat#2]
開發您好，我今天在伺服器上部署的時候遇到報錯了，但是我對npm並不是非常了解，想請問一下要如何解決
npm版本
```
[root@cent kyaru-connect.*.*]# n -V
6.5.1
```
報錯內容
```
[root@cent kyaru-connect.*.*]# npm run deploy

> kyaru-concat@0.10.0 deploy /www/wwwroot/kyaru-connect.*.*
> now --prod

sh: now: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! kyaru-concat@0.10.0 deploy: `now --prod`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the kyaru-concat@0.10.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-28T02_29_23_758Z-debug.log
```

以下是 debug 日誌 /root/.npm/_logs/2020-06-28T02_20_37_156Z-debug.log 的內容
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@6.14.4
3 info using node@v14.2.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle kyaru-concat@0.10.0~predeploy: kyaru-concat@0.10.0
6 info lifecycle kyaru-concat@0.10.0~deploy: kyaru-concat@0.10.0
7 verbose lifecycle kyaru-concat@0.10.0~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle kyaru-concat@0.10.0~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/wwwroot/kyaru-connect.*.*/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle kyaru-concat@0.10.0~deploy: CWD: /www/wwwroot/kyaru-connect.*.*
10 silly lifecycle kyaru-concat@0.10.0~deploy: Args: [ '-c', 'now --prod' ]
11 info lifecycle kyaru-concat@0.10.0~deploy: Failed to exec deploy script
12 verbose stack Error: kyaru-concat@0.10.0 deploy: `now --prod`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1051:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid kyaru-concat@0.10.0
14 verbose cwd /www/wwwroot/kyaru-connect.*.*
15 verbose Linux 5.6.10-1.el7.elrepo.x86_64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
17 verbose node v14.2.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error kyaru-concat@0.10.0 deploy: `now --prod`
23 error spawn ENOENT
24 error Failed at the kyaru-concat@0.10.0 deploy script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by ayamomiji** [comment]
有先 `npm install` 嗎?

**Comment by ayamomiji** [comment]
另外這個指令是我要從本機部署到 now.sh 才需要做的動作,
如果你是想在伺服器上執行, 使用:
```
npm install
npm run build
npm run start
```

**Comment by BH6AOV** [comment]
> 有先 `npm install` 嗎?

有的，是按照README來的

**Comment by BH6AOV** [comment]
我去試一下

**Comment by BH6AOV** [comment]
剛剛去伺服器試了一下，開放了5000端口但是會提示請求被拒絕，試了訪問一下 `./public` 裡的 `index.html` 倒是沒有報錯啦，但是整個頁面全是空白的
```html
<!DOCTYPE html>
<html lang="en">
 <head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>接頭霸王</title>
<link rel="icon" type="image/png" href="/favicon.png">
<link rel="stylesheet" href="/global.css">
<link rel="stylesheet" href="/build/bundle.css">
<script defer="" src="/build/bundle.js" type="text/javascript"></script>
<style type="text/css">
#__sound-pirate {
  margin: 0 4px 4px 4px;
  padding: 0;
  border: 0;
  box-sizing: border-box;
  width: 32px;
  position: fixed;
  bottom: 0;
  left: 0;
  z-index: 2147483647;
  cursor: pointer;
  transition: left 1s ease; }
  #__sound-pirate.__sound-pirate-at-left:hover .__sound-pirate-to-right {
    display: block; }
  #__sound-pirate.__sound-pirate-at-right:hover .__sound-pirate-to-left {
    display: block; }
  #__sound-pirate.__sound-pirate-at-right {
    left: calc(100% - 32px - 4px); }
  #__sound-pirate * {
    margin: 0;
    padding: 0;
    box-sizing: border-box; }
  #__sound-pirate .__sound-pirate-to-left, #__sound-pirate .__sound-pirate-to-right {
    display: none;
    position: absolute;
    width: 14px;
    top: 0; }
  #__sound-pirate .__sound-pirate-to-left {
    right: 100%; }
  #__sound-pirate .__sound-pirate-to-right {
    left: 100%; }
  #__sound-pirate img {
    display: block; }
  #__sound-pirate .__sound-pirate-download {
    display: block;
    transform: rotate(0turn);
    transition: transform 1s ease; }
</style>
</head>
<body>
<!---->
</body>
</html>
```

**Comment by ayamomiji** [comment]
`npm run build` 後會產生 `public/build` 目錄, 上面的
``` html
<link rel="stylesheet" href="/global.css">
<link rel="stylesheet" href="/build/bundle.css">
<script defer="" src="/build/bundle.js" type="text/javascript"></script>
```
應該都能拿到裡面的東西, 檢查一下 `public/build` 有沒有那些檔案吧

**Comment by BH6AOV** [comment]
> `npm run build` 後會產生 `public/build` 目錄, 上面的
> 
> ```
> <link rel="stylesheet" href="/global.css">
> <link rel="stylesheet" href="/build/bundle.css">
> <script defer="" src="/build/bundle.js" type="text/javascript"></script>
> ```
> 
> 應該都能拿到裡面的東西, 檢查一下 `public/build` 有沒有那些檔案吧

有確實是有啦，就是打開頁面的時候是純白的，總不能是cloudflare的原因吧
```
[root@cent build]# ls
040de459fcd91ac5.png  7703de4a4049a67f.png  bundle.js
0a5237c3f6e7a26f.png  7a494e56e019c27e.png  bundle.js.map
12616d834443b511.png  8202607259f76b5f.png  c9f5ef364009e11d.png
1261708bb57508bc.png  85a64cbb8d8e26e9.png  cc38e8f8b66cf3f2.png
1d7e1d670470b767.png  879d65f30cd71a96.png  cd2e1ca515d94397.png
289d87ea45315851.png  8a78dffa7714a939.png  d399ab06a46c47b4.png
308f9403289323ff.png  8e5329c5d3873ce6.png  d88ea25f19ba8327.png
3bd543c8df013a98.png  901b907c535b87a5.png  d9fed2745b86ccb3.png
4cad88200f67c5f0.png  919e804983f9a74a.png  e6c46697829daa2f.png
4cb4d6a167da5d26.png  9520790c4cc54ba5.png  f0379221a104d3df.png
5217f8c6f519e399.png  9c75196e776fc4e9.png  f2c4f6664e354c8b.png
5bafa5cb64a0b928.png  afb371ce695280f7.png  f56696ddb35ebba2.png
622deb59f64ac0de.png  b0f72338e8115114.png  fbfc63ee9ceb12a0.png
63fa580cfefb7408.png  bundle.css
6ceef923d66f189c.png  bundle.css.map
```

**Comment by ayamomiji** [comment]
方便給我網址或 console 底下的錯誤訊息嗎?

**Comment by BH6AOV** [comment]
> 方便給我網址或 console 底下的錯誤訊息嗎?

網址是https://kyaru-connect.ypa.moe

**Comment by BH6AOV** [comment]
> 方便給我網址或 console 底下的錯誤訊息嗎?

網址是https://kyaru-connect.ypa.moe

誒，突然能打開了？？？

**Comment by BH6AOV** [comment]
我這邊可能會對網頁做一點小更改，比如網頁簡體化還有頁腳內容的一些替換可以嗎，我會保留絕大部分原信息

**Comment by ayamomiji** [comment]
可以, 請隨意
